apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - name: nginx
          containerPort: 80
          protocol: TCP
  initContainers:
    - name: init-myservice
      image: busybox
      command: ["sh","-c","until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice to start; sleep 2; done"]
    - name: init-db
      image: busybox
      command: ["sh","-c","until nslookup mydb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo Waiting for mydb to start; sleep 2; done"]
  restartPolicy: Always
  