apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      tier: web
  template:
    metadata:
      labels:
        tier: web
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            requests:
              cpu: "0.01"
            limits:
              cpu: "0.02"
