apiVersion: v1
kind: Pod
metadata:
  name: load-test-pod
  labels:
    app: load-test
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh","-c"]
      args: ['while true; do wget -q -O- http://apache-server:80/; sleep 0.01; done']