apiVersion: v1
kind: Pod
metadata:
  name: pod-node-affinity-weights
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: label-1
                operator: In
                values:
                  - value-1
        - weight: 50
          preference:
            - matchExpressions:
                - key: label-2
                  operator: In
                  values:
                    - value-2