# Kibana Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: kube-logging
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.2.0
          ports:
            - name: kibana-port
              containerPort: 5601
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
