---
apiVersion: v1
kind: Pod
metadata:
  name: node-app-pod
  labels:
    app: node-app
spec:
  containers:
      - name: node-app-volume-mount
        image: eswarmaganti/nodejs_rest_api:latest
        command: ['/bin/sh','-c','cat /etc/config/PORT']
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: my-config
  restartPolicy: Never