---
apiVersion: v1
kind: Pod
metadata:
  name: node-api-pod
  labels:
    app: node-api
spec:
  containers:
    - name: node-pod
      image: eswarmaganti/nodejs_rest_api:latest
      env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: PORT
