# Defining the Fluentd Daemonset
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-logging
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      # tolerations to run the pods in control plane
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
          operator: Exists

      # service account 
      serviceAccount: fluentd
      serviceAccountName: fluentd

      # defining the DaemonSet Containers
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.4.2-debian-elasticsearch-1.1
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: elasticsearch.kube-logging.svc.cluster.local
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "http"
            - name: FLUENTD_SYSTEMD_CONF
              value: disable
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 512Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdocker
              mountPath: /var/lib/docker/containers
              readOnly: true
      
      # defining the volumes
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath: 
            path: /var/log
        - name: varlibdocker
          hostPath: 
            path: /var/lib/docker/containers