apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: resource-management
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "2"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "1"
